export interface IGoodItem {
  marketPrice: number;
  addedDate: string;
  color: string;
  city: string;
  imagePath: string;
  productName: string;
  freightType: number;
  freightMoney: number;
  isDeleted: number;
  lstUpdDate: string;
  id: number;
  productType: number;
  vistiCounts: number;
  createDate: string;
  quantity: number;
  address: string;
  salePrice: number;
  sellerFreight: number;
  weight: number;
  shortDescription: string;
  saleStatus: number;
  userId: number;
  volume: number;
  phone: string;
  brandId: number;
  auditStatus: number;
  categoryId: number;
}
